apiVersion: skaffold/v1beta15
kind: Config
metadata:
  name: assessment-
build:
  artifacts:
    - image: andreasgarvik/cab432-client
      context: client
    - image: andreasgarvik/cab432-server
      context: server
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - k8s\autoscaler-client.yml
      - k8s\autoscaler-server.yml
      - k8s\client.yml
      - k8s\ingress.yml
      - k8s\redis.yml
      - k8s\server.yml
profiles:
  - build:
      googleCloudBuild:
        projectId: cab432-a2
    deploy: {}
    name: GKE
