apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: serviceaccountkey
      containers:
        - name: server
          image: andreasgarvik/cab432-server
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 32Mi
              cpu: 200m
            limits:
              memory: 64Mi
              cpu: 250m
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: TWITTERAPIKEY
              valueFrom:
                secretKeyRef:
                  name: twitterapikey
                  key: TWITTERAPIKEY
            - name: TWITTERAPISECRET
              valueFrom:
                secretKeyRef:
                  name: twitterapisecret
                  key: TWITTERAPISECRET
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - port: 8080
      targetPort: 8080
